# Generated by Django 3.2.12 on 2022-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenfeng', models.CharField(max_length=20)),
                ('leijiquezhen', models.IntegerField(max_length=6)),
                ('siwang', models.IntegerField(max_length=6)),
                ('zhiyu', models.IntegerField(max_length=6)),
                ('xianyouquezhen', models.IntegerField(max_length=6)),
                ('leijiquezhenliang', models.IntegerField(max_length=6)),
                ('siwangzenliang', models.IntegerField(max_length=6)),
                ('zhiyuzengliang', models.IntegerField(max_length=6)),
                ('xianyouquezhenzengliang', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='dataout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenfeng', models.CharField(max_length=20)),
                ('leijiquezhen', models.IntegerField(max_length=6)),
                ('siwang', models.IntegerField(max_length=6)),
                ('zhiyu', models.IntegerField(max_length=6)),
                ('xianyouquezhen', models.IntegerField(max_length=6)),
                ('leijiquezhenliang', models.IntegerField(max_length=6)),
            ],
        ),
    ]
