# Generated by Django 3.2.12 on 2024-10-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datain',
        ),
        migrations.DeleteModel(
            name='dataout',
        ),
    ]
